// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class ItemDragOverlayView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Button rotateButtonLeft;
        [SerializeField] public global::UnityEngine.UI.Button rotateButtonRight;
    }
}
