// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class ItemDragOverlayForm : UGuiForm
    {
        [SerializeField] private ItemDragOverlayView _view = null;

        public ItemDragOverlayView View => _view;
    }
}
