// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class LoadoutView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.RectTransform characterListRoot;
        [SerializeField] public global::SepCore.UI.CharacterSlotItem characterSlotTemplate;
        [SerializeField] public global::UnityEngine.RectTransform weaponListRoot;
        [SerializeField] public global::SepCore.UI.WarehouseSlotItem weaponSlotTemplate;
        [SerializeField] public global::UnityEngine.RectTransform armorListRoot;
        [SerializeField] public global::SepCore.UI.WarehouseSlotItem armorSlotTemplate;
        [SerializeField] public global::SepCore.UI.CharacterPreviewForm characterPreviewForm;
    }
}
