// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class LoadoutForm : UGuiForm
    {
        [SerializeField] private LoadoutView _view = null;

        public LoadoutView View => _view;
    }
}
