// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class ItemDetailsView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Image itemDetailIcon;
        [SerializeField] public global::TMPro.TextMeshProUGUI itemDetailNameText;
        [SerializeField] public global::TMPro.TextMeshProUGUI itemDetailTypeText;
        [SerializeField] public global::SepCore.UI.FormatTextUI hpFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI atkFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI mpFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI matFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI speedFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI stackFormatText;
        [SerializeField] public global::TMPro.TextMeshProUGUI itemDetailDescriptionText;
        [SerializeField] public global::UnityEngine.UI.Button moveBackpackButton;
    }
}
