// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class FadeView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.CanvasGroup maskCanvasGroup;
    }
}
