// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class FadeForm : UGuiForm
    {
        [SerializeField] private FadeView _view = null;

        public FadeView View => _view;
    }
}
