// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class HomeForm : UGuiForm
    {
        [SerializeField] private HomeView _view = null;

        public HomeView View => _view;
    }
}
