// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class RoundBackpackForm : UGuiForm
    {
        [SerializeField] private RoundBackpackView _view = null;

        public RoundBackpackView View => _view;
    }
}
