// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class RoundBackpackView : MonoBehaviour
    {
        [SerializeField] public global::TMPro.TextMeshProUGUI timerText;
        [SerializeField] public global::UnityEngine.UI.Button closeButton;
        [SerializeField] public global::SepCore.UI.BackpackForm backpackForm;
        [SerializeField] public global::SepCore.UI.CharacterForm characterForm;
    }
}
