// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class BackpackForm : UGuiForm
    {
        [SerializeField] private BackpackView _view = null;

        public BackpackView View => _view;
    }
}
