// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class BackpackView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.RectTransform backpackSlotRoot;
        [SerializeField] public global::SepCore.UI.WarehouseSlotItem backpackSlotTemplate;
        [SerializeField] public global::SepCore.UI.FormatTextUI safeCapacityFormatText;
        [SerializeField] public global::SepCore.UI.WarehouseSlotItem safeCaseSlotTemplate;
    }
}
