// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class RoundSettlementView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Image resultAccent;
        [SerializeField] public global::TMPro.TextMeshProUGUI resultText;
        [SerializeField] public global::TMPro.TextMeshProUGUI totalValueText;
        [SerializeField] public global::SepCore.UI.FormatTextUI elapsedTime;
        [SerializeField] public global::SepCore.UI.FormatTextUI redLootCount;
        [SerializeField] public global::UnityEngine.RectTransform redLootViewport;
        [SerializeField] public global::UnityEngine.RectTransform redLootContent;
        [SerializeField] public global::SepCore.UI.RedLootItem redLootItemTemplate;
        [SerializeField] public global::UnityEngine.RectTransform emptyRedLootState;
        [SerializeField] public global::UnityEngine.RectTransform retainedHint;
        [SerializeField] public global::UnityEngine.UI.Button returnToLobbyButton;
    }
}
