// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class RoundSettlementForm : UGuiForm
    {
        [SerializeField] private RoundSettlementView _view = null;

        public RoundSettlementView View => _view;
    }
}
