// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class DeploymentBriefingView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.CanvasGroup canvasGroup;
        [SerializeField] public global::UnityEngine.CanvasGroup maskCanvasGroup;
        [SerializeField] public global::UnityEngine.CanvasGroup bannerCanvasGroup;
        [SerializeField] public global::TMPro.TextMeshProUGUI threatTierText;
        [SerializeField] public global::TMPro.TextMeshProUGUI mapNameText;
        [SerializeField] public global::TMPro.TextMeshProUGUI subInfoText;
    }
}
