// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class DeploymentBriefingForm : UGuiForm
    {
        [SerializeField] private DeploymentBriefingView _view = null;

        public DeploymentBriefingView View => _view;
    }
}
