// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class SquadView : MonoBehaviour
    {
        [SerializeField] public global::SepCore.UI.FormatTextUI squadMemberFormatText;
        [SerializeField] public global::UnityEngine.RectTransform characterSlotRoot;
        [SerializeField] public global::SepCore.UI.CharacterSlotItem characterSlotTemplate;
    }
}
