// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class RoundHUDView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.RawImage minimapTexture;
        [SerializeField] public global::UnityEngine.RectTransform mapEmptyState;
        [SerializeField] public global::UnityEngine.RectTransform minimapMarkers;
        [SerializeField] public global::UnityEngine.RectTransform playerMarker;
        [SerializeField] public global::UnityEngine.RectTransform extractionMarker;
        [SerializeField] public global::TMPro.TextMeshProUGUI extractionStatusText;
        [SerializeField] public global::SepCore.UI.FormatTextUI remainingTime;
        [SerializeField] public global::UnityEngine.UI.Button settingsButton;
        [SerializeField] public global::SepCore.UI.FormatTextUI freeSlotsValue;
        [SerializeField] public global::TMPro.TextMeshProUGUI lootValueText;
        [SerializeField] public global::UnityEngine.UI.Button backpackButton;
        [SerializeField] public global::SepCore.UI.FormatTextUI openBackpack;
        [SerializeField] public global::UnityEngine.RectTransform extractionNotice;
        [SerializeField] public global::SepCore.UI.FormatTextUI extractionNoticeTitle;
        [SerializeField] public global::SepCore.UI.FormatTextUI extractionNoticeHint;
    }
}
