// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class RoundHUDForm : UGuiForm
    {
        [SerializeField] private RoundHUDView _view = null;

        public RoundHUDView View => _view;
    }
}
