// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class CharacterView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Toggle characterTab01Toggle;
        [SerializeField] public global::UnityEngine.UI.Toggle characterTab02Toggle;
        [SerializeField] public global::UnityEngine.UI.Toggle characterTab03Toggle;
        [SerializeField] public global::UnityEngine.UI.Toggle characterTab04Toggle;
        [SerializeField] public global::UnityEngine.UI.Image characterIcon;
        [SerializeField] public global::SepCore.UI.FormatTextUI memberHpFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI memberMpFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI attackFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI magicFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI speedFormatText;
        [SerializeField] public global::UnityEngine.UI.Image weaponIcon;
        [SerializeField] public global::TMPro.TextMeshProUGUI weaponNameText;
        [SerializeField] public global::UnityEngine.UI.Image armorIcon;
        [SerializeField] public global::TMPro.TextMeshProUGUI armorNameText;
        [SerializeField] public global::UnityEngine.UI.Image selectedItemIcon;
        [SerializeField] public global::SepCore.UI.FormatTextUI selectedItemNameFormatText;
        [SerializeField] public global::TMPro.TextMeshProUGUI selectedItemRarityText;
        [SerializeField] public global::UnityEngine.UI.Button moveToSafeButton;
    }
}
