// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class CharacterForm : UGuiForm
    {
        [SerializeField] private CharacterView _view = null;

        public CharacterView View => _view;
    }
}
