// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class CharacterPreviewView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Image characterIcon;
        [SerializeField] public global::TMPro.TextMeshProUGUI characterNameText;
        [SerializeField] public global::SepCore.UI.FormatTextUI hpFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI mpFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI atkFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI matFormatText;
        [SerializeField] public global::SepCore.UI.FormatTextUI speedFormatText;
        [SerializeField] public global::UnityEngine.UI.Button weaponSlotButton;
        [SerializeField] public global::UnityEngine.UI.Image weaponIcon;
        [SerializeField] public global::TMPro.TextMeshProUGUI weaponNameText;
        [SerializeField] public global::UnityEngine.UI.Button armorSlotButton;
        [SerializeField] public global::UnityEngine.UI.Image armorIcon;
        [SerializeField] public global::TMPro.TextMeshProUGUI armorNameText;
    }
}
