// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class CharacterPreviewForm : UGuiForm
    {
        [SerializeField] private CharacterPreviewView _view = null;

        public CharacterPreviewView View => _view;
    }
}
